apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v221219-c92ed8152.clusterworkspaces.tenancy.kcp.dev
  - v221219-c92ed8152.workspaces.tenancy.kcp.dev
  - v221219-c92ed8152.workspacetypes.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
