apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v221128-9e4040046.clusterworkspacetypes.tenancy.kcp.dev
  - v221204-5bf97087f.clusterworkspaces.tenancy.kcp.dev
  - v221204-5bf97087f.workspaces.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
