apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v221212-22eb97777.clusterworkspacetypes.tenancy.kcp.dev
  - v221216-5977dcf75.workspaces.tenancy.kcp.dev
  - v221216-7a674974c.clusterworkspaces.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
