apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v221216-23f21069b.workspacetypes.tenancy.kcp.dev
  - v221216-333f94aab.clusterworkspaces.tenancy.kcp.dev
  - v221216-333f94aab.workspaces.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
